[package]
name = "melody_cli"
version = "0.1.1"
edition = "2021"
rust-version = "1.58.0"

[dependencies]
clap = { version = "3.0.7", features = ["derive"] }
colored = "2.0.0"
melody_compiler = { version = "0.1.1", path = "../melody_compiler" }

[[bin]]
name = "melody"
path = "./src/main.rs"
