[package]
name = "melody_cli"
description = "A CLI wrapping the Melody language compiler"
homepage = "https://github.com/yoav-lavi/melody"
repository = "https://github.com/yoav-lavi/melody"
readme = "README.md"
version = "0.13.2"
edition = "2021"
rust-version = "1.58.0"
license = "MIT"
keywords = ["melody", "melodylang", "language", "cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "3.0.7", features = ["derive"] }
colored = "2.0.0"
melody_compiler = { version = "0.13.2", path = "../melody_compiler" }

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
unindent = "0.1.8"
tempfile = "3"

[[bin]]
name = "melody"
path = "./src/main.rs"
