on: [push]

name: build

jobs:
  check:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cargo-tarpaulin
        run: "cargo install cargo-tarpaulin -f"

      - name: Run cargo-tarpaulin
        run: "cargo tarpaulin --out Xml --verbose --all-features --run-types Tests,Doctests"

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
