on: [push]

name: build

jobs:
  check:
    name: Measure and upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-tarpaulin
        run: "cargo install cargo-tarpaulin -f"

      - name: Run cargo-tarpaulin
        run: "cargo tarpaulin --out Xml --verbose --all-features --run-types Tests,Doctests"

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v2
